pipelines:
  ContractEventsPipeline:
    source:
      type: "BufferedStorageSourceAdapter"
      config:
        bucket_name: "obsrvr-stellar-ledger-data-testnet-data/landing/"
        network: "testnet"
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 2
        end_ledger: 700
        ledgers_per_file: 1
        files_per_partition: 64000
    processors:
      - type: "flow/processor/contract-events"
        config:
          network_passphrase: "Test SDF Network ; September 2015"
      - type: "flow/processor/contract-filter"
        config:
          contract_id: "CA2B6MIEWVZQZGOBLY6POMT7RGQK3GVJ3XBDNDKCYUYNCN65T6KWGWJE"
    consumers:
      - type: "SaveToZeroMQ"
        config:
          address: "tcp://127.0.0.1:5555"