pipelines:
  SoroswapPipeline:
    source:
      type: "BufferedStorageSourceAdapter"
      config:
        bucket_name: "obsrvr-stellar-ledger-data-mainnet-data/landing/"
        network: "mainnet"
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 56146570
        ledgers_per_file: 1
        files_per_partition: 64000
    processors:
      - type: "flow/processor/latest-ledger"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
    consumers:
      - type: "SaveToZeroMQ"
        config:
          address: "tcp://127.0.0.1:5556"
