pipelines:
  SoroswapRouterPipeline:
    source:
      type: "BufferedStorageSourceAdapter"
      config:
        bucket_name: "obsrvr-stellar-ledger-data-mainnet-data/landing/"
        network: "mainnet"
        num_workers: 10
        retry_limit: 3
        retry_wait: 5
        start_ledger: 56075000
        ledgers_per_file: 1
        files_per_partition: 64000
    processors:
      - type: "flow/processor/contract-events"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
      - type: "flow/processor/soroswap-router"
        config: {}
    consumers:
      - type: "flow/consumer/soroswap-router-sqlite"
        config:
          db_path: "flow_data_soroswap_router_2.db"
      - type: "SaveToZeroMQ"
        config:
          address: "tcp://127.0.0.1:5555" 