pipeline:
  name: wasm-sample-pipeline
  description: Pipeline demonstrating WASM plugin usage

  # Source for events - using a simple RPC source
  source:
    name: flow-blockchain
    type: rpc
    config:
      access_node: access.mainnet.nodes.onflow.org:9000
      collection_guarantee_included: true
      transaction_result: true
      block_sealed: true
      heartbeat:
        interval_seconds: 30

  # Processors 
  processors:
    # Basic RPC processor
    - name: rpc-processor
      type: processor
      plugin: ./plugins/flow-processor-rpc.so
    
    # WASM sample consumer plugin
    - name: wasm-sample
      type: consumer
      plugin: ./plugins/wasm-sample.wasm
      config:
        example_key: "example_value"
        demo_setting: true
        numeric_value: 42

    # SQLite consumer for persistence
    - name: sqlite
      type: consumer
      plugin: ./plugins/flow-consumer-sqlite.so
      config:
        database_path: "./data/flow.db"
        schema_path: "./plugins/schema.sql"

graphql:
  enabled: true
  port: 8080

schema_registry:
  enabled: true
  port: 8081 