pipelines:
  SimpleWasmTestPipeline:
    source:
      type: "TestSource"  # This doesn't need to exist; we just want to check plugin loading
      config:
        dummy: true
    processors:
      - type: "flow/processor/latest-ledger"
        plugin: "DIR_PLACEHOLDER/plugins/flow-processor-latest-ledger.wasm"
        config:
          network_passphrase: "Public Global Stellar Network ; September 2015"
    consumers:
      - type: "TestConsumer"  # This doesn't need to exist; we just want to check plugin loading
        config:
          dummy: true 